name: Release

on:
  push:
    tags: ['v*']

permissions: {}

jobs:
  release:
    name: Release
    uses: praxi-labs/ci/.github/workflows/action-release.yml@v1
    permissions:
      contents: write
